/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fun_jni_JavaJNI */

#ifndef _Included_com_fun_jni_JavaJNI
#define _Included_com_fun_jni_JavaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fun_jni_JavaJNI
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fun_jni_JavaJNI_printHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
